apiVersion: v1
kind: Namespace
metadata:
  name: codechange-tracker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: codechange-tracker
data:
  ENVIRONMENT: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: codechange-tracker
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@postgres:5432/codechange_tracker?sslmode=disable"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "your-super-secret-jwt-key"
  OPENAI_API_KEY: "your-openai-api-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codechange-tracker
  namespace: codechange-tracker
  labels:
    app: codechange-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codechange-tracker
  template:
    metadata:
      labels:
        app: codechange-tracker
    spec:
      containers:
      - name: app
        image: codechange-tracker:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: codechange-tracker-service
  namespace: codechange-tracker
spec:
  selector:
    app: codechange-tracker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codechange-tracker-ingress
  namespace: codechange-tracker
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: codechange-tracker.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codechange-tracker-service
            port:
              number: 80